version: '3.8'

services:
  frontend:
    build:
      context: ./movie-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./movie-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=root
      - DB_NAME=movie_library
      - PORT=3001
      - JWT_SECRET=925ee3bb7ddb985702060a5bd2ee1110eab9125c1c0c585195a8cc89c171c3e8
      - OMDB_API_KEY=5cce4d33
    depends_on:
      - db
    volumes:
      - ./backend/logs:/usr/src/app/logs

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: movie_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
